#!/bin/sh
read -p "This will erase most of your existing configuration files. Are you sure? " -n 1
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
echo ""
pushd $HOME

rm -fv .emacs.d
rm -fv .zshrc
rm -fv .Xresources
rm -fv .Xmodmap
rm -fv .pythonrc.py
rm -fv .inputrc
rm -fv .gitconfig
rm -fv .gitignore
ln -sv .zerorc/.emacs.d .
ln -sv .zerorc/.zshrc .
ln -sv .zerorc/.Xresources .
ln -sv .zerorc/.Xmodmap .
ln -sv .zerorc/.pythonrc.py .
ln -sv .zerorc/.inputrc .
ln -sv .zerorc/.gitconfig .
ln -sv .zerorc/.gitignore-global .gitignore
popd
