;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line
        beginning-of-buffer
        c-electric-star
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        compile-goto-error
        delete-indentation
        duplicate-line-or-region-below
        electric-newline-and-maybe-indent
        end-of-buffer
        eval-print-last-sexp
        haml-electric-backspace
        ido-find-file
        indent-for-tab-command
        indent-rigidly
        jedi:dot-complete
        jinja2-insert-tag
        jinja2-insert-var
        kill-region
        kmacro-set-counter
        kmacro-start-macro-or-insert-counter
        move-text-down
        nxml-electric-slash
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        repeat
        sgml-close-tag
        sgml-maybe-name-self
        sgml-slash
        transpose-words
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        complete-symbol
        emmet-expand-line
        emmet-preview-abort
        ido-switch-buffer
        markdown-exdent-or-delete
        mouse-secondary-save-then-kill
        mouse-set-region
        mouse-set-secondary
        multiple-cursors-mode
        ))
