;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line
        beginning-of-buffer
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        compile-goto-error
        delete-indentation
        duplicate-line-or-region-below
        eval-print-last-sexp
        haml-electric-backspace
        ido-find-file
        indent-for-tab-command
        indent-rigidly
        jedi:dot-complete
        kill-region
        kmacro-start-macro-or-insert-counter
        move-text-down
        nxml-electric-slash
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        repeat
        sgml-close-tag
        sgml-maybe-name-self
        sgml-slash
        transpose-words
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        mouse-secondary-save-then-kill
        mouse-set-secondary
        ))
