(source gnu)
(source melpa)
(source marmalade)
(source org)

;; Theme
(depends-on "noctilux-theme")
(depends-on "soothe-theme")

;; Tools
(depends-on "ack-and-a-half")
(depends-on "magit")
(depends-on "move-text")
(depends-on "multiple-cursors")
(depends-on "pyregexp")
(depends-on "github-browse-file")
(depends-on "emmet-mode")
(depends-on "fiplr")

;; UI
(depends-on "git-gutter")
(depends-on "rainbow-delimiters")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "pretty-mode")
(depends-on "rainbow-mode")
(depends-on "window-numbering")
(depends-on "buffer-move")

;; Modes
(depends-on "coffee-mode")
(depends-on "markdown-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "jinja2-mode")
(depends-on "js3-mode")

;; Check
(depends-on "flycheck")
