(source gnu)
(source melpa)

;; Theme
(depends-on "noctilux-theme")
(depends-on "soothe-theme")

;; Tools
(depends-on "ag")
(depends-on "magit")
(depends-on "move-text")
(depends-on "multiple-cursors")
(depends-on "visual-regexp-steroids")
(depends-on "github-browse-file")
(depends-on "emmet-mode")
(depends-on "fiplr")
(depends-on "elpy")

;; UI
(depends-on "git-gutter")
(depends-on "highlight-parentheses")
(depends-on "highlight-numbers")
(depends-on "highlight-symbol")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "pretty-mode")
(depends-on "rainbow-mode")
(depends-on "window-numbering")
(depends-on "buffer-move")
;; (depends-on "color-identifiers-mode")

;; Modes
(depends-on "coffee-mode")
(depends-on "markdown-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "jinja2-mode")
(depends-on "js3-mode")
(depends-on "glsl-mode")
(depends-on "lua-mode")
(depends-on "yaml-mode")
(depends-on "tornado-template-mode")

;; Check
(depends-on "flycheck")

;; Deps
(depends-on "dash")
(depends-on "dash-functional")

;; Misc
(depends-on "speed-type")
